version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped

  # Development service for local development
  frontend-dev:
    image: node:20-alpine
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    ports:
      - "3333:5173"
    expose:
      - "5173"
    network_mode: "host"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    env_file:
      - .env
    restart: unless-stopped

volumes:
  node_modules:
